@baseURL = http://localhost:3000/api/products
@id = 680e2308bd6b25e61b43fca9

### GET - Listar todos os produtos
GET {{baseURL}}

### GET - product pelo ID
GET {{baseURL}}/{{id}}

### PSOT - CrIar novo produto
POST {{baseURL}}
Content-Type: application/json

{
  "cod_produto": "PRD002",
  "name": "Produto Example",
  "price": 120.50,
  "description": "Exemplo de produto",
  "category": "Categoria Exemplo"
}

### PUT - Atualizar o produto pelo ID
PUT {{baseURL}}/{{id}}
Content-Type: application/json

{
  "cod_produto": "PRD002",
  "name": "Produto Atualizado",
  "price": 150.00,
  "description": "Descrição atualizada",
  "category": "Categoria Atualizada"
}

### DELETE - deletar produto pelo id
DELETE {{baseURL}}/{{id}}
