@baseURL = http://localhost:3000/api/municipios
@id = 1

GET {{baseURL}}/{{id}}
Content-Type: application/json

GET {{baseURL}}


DELETE {{baseURL}}/{{id}}
Content-Type: application/json


POST {{baseURL}}
Content-Type: application/json


PUT {{baseURL}}/{{id}}
Content-Type: application/json